#pragma once

#include <stdint.h>

#include <win32\impl\EnumFromUdtConst.h>

#include <win32\Windows.Win32.AI.MachineLearning.DirectML.h>
#include <win32\Windows.Win32.AI.MachineLearning.WinML.h>
#include <win32\Windows.Win32.Data.HtmlHelp.h>
#include <win32\Windows.Win32.Data.RightsManagement.h>
#include <win32\Windows.Win32.Data.Xml.MsXml.h>
#include <win32\Windows.Win32.Data.Xml.XmlLite.h>
#include <win32\Windows.Win32.Devices.AllJoyn.h>
#include <win32\Windows.Win32.Devices.Beep.h>
#include <win32\Windows.Win32.Devices.BiometricFramework.h>
#include <win32\Windows.Win32.Devices.Bluetooth.h>
#include <win32\Windows.Win32.Devices.Cdrom.h>
#include <win32\Windows.Win32.Devices.Communication.h>
#include <win32\Windows.Win32.Devices.DeviceAccess.h>
#include <win32\Windows.Win32.Devices.DeviceAndDriverInstallation.h>
#include <win32\Windows.Win32.Devices.DeviceQuery.h>
#include <win32\Windows.Win32.Devices.Display.h>
#include <win32\Windows.Win32.Devices.Dvd.h>
#include <win32\Windows.Win32.Devices.Enumeration.Pnp.h>
#include <win32\Windows.Win32.Devices.Fax.h>
#include <win32\Windows.Win32.Devices.FunctionDiscovery.h>
#include <win32\Windows.Win32.Devices.Geolocation.h>
#include <win32\Windows.Win32.Devices.h>
#include <win32\Windows.Win32.Devices.HumanInterfaceDevice.h>
#include <win32\Windows.Win32.Devices.ImageAcquisition.h>
#include <win32\Windows.Win32.Devices.Nfc.h>
#include <win32\Windows.Win32.Devices.Nfp.h>
#include <win32\Windows.Win32.Devices.PortableDevices.h>
#include <win32\Windows.Win32.Devices.Properties.h>
#include <win32\Windows.Win32.Devices.Pwm.h>
#include <win32\Windows.Win32.Devices.Sensors.h>
#include <win32\Windows.Win32.Devices.SerialCommunication.h>
#include <win32\Windows.Win32.Devices.Tapi.h>
#include <win32\Windows.Win32.Devices.Usb.h>
#include <win32\Windows.Win32.Devices.WebServicesOnDevices.h>
#include <win32\Windows.Win32.Foundation.h>
#include <win32\Windows.Win32.Foundation.Metadata.h>
#include <win32\Windows.Win32.Gaming.h>
#include <win32\Windows.Win32.Globalization.h>
#include <win32\Windows.Win32.Graphics.CompositionSwapchain.h>
#include <win32\Windows.Win32.Graphics.Direct2D.Common.h>
#include <win32\Windows.Win32.Graphics.Direct2D.h>
#include <win32\Windows.Win32.Graphics.Direct3D.Dxc.h>
#include <win32\Windows.Win32.Graphics.Direct3D.Fxc.h>
#include <win32\Windows.Win32.Graphics.Direct3D.h>
#include <win32\Windows.Win32.Graphics.Direct3D9.h>
#include <win32\Windows.Win32.Graphics.Direct3D9on12.h>
#include <win32\Windows.Win32.Graphics.Direct3D10.h>
#include <win32\Windows.Win32.Graphics.Direct3D11.h>
#include <win32\Windows.Win32.Graphics.Direct3D11on12.h>
#include <win32\Windows.Win32.Graphics.Direct3D12.h>
#include <win32\Windows.Win32.Graphics.DirectComposition.h>
#include <win32\Windows.Win32.Graphics.DirectDraw.h>
#include <win32\Windows.Win32.Graphics.DirectManipulation.h>
#include <win32\Windows.Win32.Graphics.DirectWrite.h>
#include <win32\Windows.Win32.Graphics.Dwm.h>
#include <win32\Windows.Win32.Graphics.DXCore.h>
#include <win32\Windows.Win32.Graphics.Dxgi.Common.h>
#include <win32\Windows.Win32.Graphics.Dxgi.h>
#include <win32\Windows.Win32.Graphics.Gdi.h>
#include <win32\Windows.Win32.Graphics.GdiPlus.h>
#include <win32\Windows.Win32.Graphics.Hlsl.h>
#include <win32\Windows.Win32.Graphics.Imaging.D2D.h>
#include <win32\Windows.Win32.Graphics.Imaging.h>
#include <win32\Windows.Win32.Graphics.OpenGL.h>
#include <win32\Windows.Win32.Graphics.Printing.h>
#include <win32\Windows.Win32.Graphics.Printing.PrintTicket.h>
#include <win32\Windows.Win32.Management.MobileDeviceManagementRegistration.h>
#include <win32\Windows.Win32.Media.Audio.Apo.h>
#include <win32\Windows.Win32.Media.Audio.DirectMusic.h>
#include <win32\Windows.Win32.Media.Audio.DirectSound.h>
#include <win32\Windows.Win32.Media.Audio.Endpoints.h>
#include <win32\Windows.Win32.Media.Audio.h>
#include <win32\Windows.Win32.Media.Audio.XAudio2.h>
#include <win32\Windows.Win32.Media.DeviceManager.h>
#include <win32\Windows.Win32.Media.DirectShow.h>
#include <win32\Windows.Win32.Media.DirectShow.Tv.h>
#include <win32\Windows.Win32.Media.DirectShow.Xml.h>
#include <win32\Windows.Win32.Media.DxMediaObjects.h>
#include <win32\Windows.Win32.Media.h>
#include <win32\Windows.Win32.Media.KernelStreaming.h>
#include <win32\Windows.Win32.Media.LibrarySharingServices.h>
#include <win32\Windows.Win32.Media.MediaFoundation.h>
#include <win32\Windows.Win32.Media.MediaPlayer.h>
#include <win32\Windows.Win32.Media.Multimedia.h>
#include <win32\Windows.Win32.Media.PictureAcquisition.h>
#include <win32\Windows.Win32.Media.Speech.h>
#include <win32\Windows.Win32.Media.Streaming.h>
#include <win32\Windows.Win32.Media.WindowsMediaFormat.h>
#include <win32\Windows.Win32.Networking.ActiveDirectory.h>
#include <win32\Windows.Win32.Networking.BackgroundIntelligentTransferService.h>
#include <win32\Windows.Win32.Networking.Clustering.h>
#include <win32\Windows.Win32.Networking.HttpServer.h>
#include <win32\Windows.Win32.Networking.Ldap.h>
#include <win32\Windows.Win32.Networking.NetworkListManager.h>
#include <win32\Windows.Win32.Networking.RemoteDifferentialCompression.h>
#include <win32\Windows.Win32.Networking.WebSocket.h>
#include <win32\Windows.Win32.Networking.WindowsWebServices.h>
#include <win32\Windows.Win32.Networking.WinHttp.h>
#include <win32\Windows.Win32.Networking.WinInet.h>
#include <win32\Windows.Win32.Networking.WinSock.h>
#include <win32\Windows.Win32.NetworkManagement.Dhcp.h>
#include <win32\Windows.Win32.NetworkManagement.Dns.h>
#include <win32\Windows.Win32.NetworkManagement.InternetConnectionWizard.h>
#include <win32\Windows.Win32.NetworkManagement.IpHelper.h>
#include <win32\Windows.Win32.NetworkManagement.MobileBroadband.h>
#include <win32\Windows.Win32.NetworkManagement.Multicast.h>
#include <win32\Windows.Win32.NetworkManagement.Ndis.h>
#include <win32\Windows.Win32.NetworkManagement.NetBios.h>
#include <win32\Windows.Win32.NetworkManagement.NetManagement.h>
#include <win32\Windows.Win32.NetworkManagement.NetShell.h>
#include <win32\Windows.Win32.NetworkManagement.NetworkDiagnosticsFramework.h>
#include <win32\Windows.Win32.NetworkManagement.NetworkPolicyServer.h>
#include <win32\Windows.Win32.NetworkManagement.P2P.h>
#include <win32\Windows.Win32.NetworkManagement.QoS.h>
#include <win32\Windows.Win32.NetworkManagement.Rras.h>
#include <win32\Windows.Win32.NetworkManagement.Snmp.h>
#include <win32\Windows.Win32.NetworkManagement.WebDav.h>
#include <win32\Windows.Win32.NetworkManagement.WiFi.h>
#include <win32\Windows.Win32.NetworkManagement.WindowsConnectionManager.h>
#include <win32\Windows.Win32.NetworkManagement.WindowsConnectNow.h>
#include <win32\Windows.Win32.NetworkManagement.WindowsFilteringPlatform.h>
#include <win32\Windows.Win32.NetworkManagement.WindowsFirewall.h>
#include <win32\Windows.Win32.NetworkManagement.WindowsNetworkVirtualization.h>
#include <win32\Windows.Win32.NetworkManagement.WNet.h>
#include <win32\Windows.Win32.Security.AppLocker.h>
#include <win32\Windows.Win32.Security.Authentication.Identity.h>
#include <win32\Windows.Win32.Security.Authentication.Identity.Provider.h>
#include <win32\Windows.Win32.Security.Authorization.h>
#include <win32\Windows.Win32.Security.Authorization.UI.h>
#include <win32\Windows.Win32.Security.ConfigurationSnapin.h>
#include <win32\Windows.Win32.Security.Credentials.h>
#include <win32\Windows.Win32.Security.Cryptography.Catalog.h>
#include <win32\Windows.Win32.Security.Cryptography.Certificates.h>
#include <win32\Windows.Win32.Security.Cryptography.h>
#include <win32\Windows.Win32.Security.Cryptography.Sip.h>
#include <win32\Windows.Win32.Security.Cryptography.UI.h>
#include <win32\Windows.Win32.Security.DiagnosticDataQuery.h>
#include <win32\Windows.Win32.Security.DirectoryServices.h>
#include <win32\Windows.Win32.Security.EnterpriseData.h>
#include <win32\Windows.Win32.Security.ExtensibleAuthenticationProtocol.h>
#include <win32\Windows.Win32.Security.h>
#include <win32\Windows.Win32.Security.Isolation.h>
#include <win32\Windows.Win32.Security.LicenseProtection.h>
#include <win32\Windows.Win32.Security.NetworkAccessProtection.h>
#include <win32\Windows.Win32.Security.Tpm.h>
#include <win32\Windows.Win32.Security.WinTrust.h>
#include <win32\Windows.Win32.Security.WinWlx.h>
#include <win32\Windows.Win32.Storage.Cabinets.h>
#include <win32\Windows.Win32.Storage.CloudFilters.h>
#include <win32\Windows.Win32.Storage.Compression.h>
#include <win32\Windows.Win32.Storage.DataDeduplication.h>
#include <win32\Windows.Win32.Storage.DistributedFileSystem.h>
#include <win32\Windows.Win32.Storage.EnhancedStorage.h>
#include <win32\Windows.Win32.Storage.FileHistory.h>
#include <win32\Windows.Win32.Storage.FileServerResourceManager.h>
#include <win32\Windows.Win32.Storage.FileSystem.h>
#include <win32\Windows.Win32.Storage.Imapi.h>
#include <win32\Windows.Win32.Storage.IndexServer.h>
#include <win32\Windows.Win32.Storage.InstallableFileSystems.h>
#include <win32\Windows.Win32.Storage.IscsiDisc.h>
#include <win32\Windows.Win32.Storage.Jet.h>
#include <win32\Windows.Win32.Storage.Nvme.h>
#include <win32\Windows.Win32.Storage.OfflineFiles.h>
#include <win32\Windows.Win32.Storage.OperationRecorder.h>
#include <win32\Windows.Win32.Storage.Packaging.Appx.h>
#include <win32\Windows.Win32.Storage.Packaging.Opc.h>
#include <win32\Windows.Win32.Storage.ProjectedFileSystem.h>
#include <win32\Windows.Win32.Storage.StructuredStorage.h>
#include <win32\Windows.Win32.Storage.Vhd.h>
#include <win32\Windows.Win32.Storage.VirtualDiskService.h>
#include <win32\Windows.Win32.Storage.Vss.h>
#include <win32\Windows.Win32.Storage.Xps.h>
#include <win32\Windows.Win32.Storage.Xps.Printing.h>
#include <win32\Windows.Win32.System.AddressBook.h>
#include <win32\Windows.Win32.System.Antimalware.h>
#include <win32\Windows.Win32.System.ApplicationInstallationAndServicing.h>
#include <win32\Windows.Win32.System.ApplicationVerifier.h>
#include <win32\Windows.Win32.System.AssessmentTool.h>
#include <win32\Windows.Win32.System.ClrHosting.h>
#include <win32\Windows.Win32.System.Com.CallObj.h>
#include <win32\Windows.Win32.System.Com.ChannelCredentials.h>
#include <win32\Windows.Win32.System.Com.Events.h>
#include <win32\Windows.Win32.System.Com.h>
#include <win32\Windows.Win32.System.Com.Marshal.h>
#include <win32\Windows.Win32.System.Com.StructuredStorage.h>
#include <win32\Windows.Win32.System.Com.UI.h>
#include <win32\Windows.Win32.System.Com.Urlmon.h>
#include <win32\Windows.Win32.System.ComponentServices.h>
#include <win32\Windows.Win32.System.Console.h>
#include <win32\Windows.Win32.System.Contacts.h>
#include <win32\Windows.Win32.System.CorrelationVector.h>
#include <win32\Windows.Win32.System.DataExchange.h>
#include <win32\Windows.Win32.System.DeploymentServices.h>
#include <win32\Windows.Win32.System.DesktopSharing.h>
#include <win32\Windows.Win32.System.DeveloperLicensing.h>
#include <win32\Windows.Win32.System.Diagnostics.Ceip.h>
#include <win32\Windows.Win32.System.Diagnostics.ClrProfiling.h>
#include <win32\Windows.Win32.System.Diagnostics.Debug.ActiveScript.h>
#include <win32\Windows.Win32.System.Diagnostics.Debug.Extensions.h>
#include <win32\Windows.Win32.System.Diagnostics.Debug.h>
#include <win32\Windows.Win32.System.Diagnostics.Debug.WebApp.h>
#include <win32\Windows.Win32.System.Diagnostics.Etw.h>
#include <win32\Windows.Win32.System.Diagnostics.ProcessSnapshotting.h>
#include <win32\Windows.Win32.System.Diagnostics.ToolHelp.h>
#include <win32\Windows.Win32.System.Diagnostics.TraceLogging.h>
#include <win32\Windows.Win32.System.DistributedTransactionCoordinator.h>
#include <win32\Windows.Win32.System.Environment.h>
#include <win32\Windows.Win32.System.ErrorReporting.h>
#include <win32\Windows.Win32.System.EventCollector.h>
#include <win32\Windows.Win32.System.EventLog.h>
#include <win32\Windows.Win32.System.EventNotificationService.h>
#include <win32\Windows.Win32.System.GroupPolicy.h>
#include <win32\Windows.Win32.System.HostCompute.h>
#include <win32\Windows.Win32.System.HostComputeNetwork.h>
#include <win32\Windows.Win32.System.HostComputeSystem.h>
#include <win32\Windows.Win32.System.Hypervisor.h>
#include <win32\Windows.Win32.System.Iis.h>
#include <win32\Windows.Win32.System.IO.h>
#include <win32\Windows.Win32.System.Ioctl.h>
#include <win32\Windows.Win32.System.JobObjects.h>
#include <win32\Windows.Win32.System.Js.h>
#include <win32\Windows.Win32.System.Kernel.h>
#include <win32\Windows.Win32.System.LibraryLoader.h>
#include <win32\Windows.Win32.System.Mailslots.h>
#include <win32\Windows.Win32.System.Mapi.h>
#include <win32\Windows.Win32.System.Memory.h>
#include <win32\Windows.Win32.System.Memory.NonVolatile.h>
#include <win32\Windows.Win32.System.MessageQueuing.h>
#include <win32\Windows.Win32.System.MixedReality.h>
#include <win32\Windows.Win32.System.Mmc.h>
#include <win32\Windows.Win32.System.Ole.h>
#include <win32\Windows.Win32.System.ParentalControls.h>
#include <win32\Windows.Win32.System.PasswordManagement.h>
#include <win32\Windows.Win32.System.Performance.h>
#include <win32\Windows.Win32.System.Performance.HardwareCounterProfiling.h>
#include <win32\Windows.Win32.System.Pipes.h>
#include <win32\Windows.Win32.System.Power.h>
#include <win32\Windows.Win32.System.ProcessStatus.h>
#include <win32\Windows.Win32.System.RealTimeCommunications.h>
#include <win32\Windows.Win32.System.Recovery.h>
#include <win32\Windows.Win32.System.Registry.h>
#include <win32\Windows.Win32.System.RemoteAssistance.h>
#include <win32\Windows.Win32.System.RemoteDesktop.h>
#include <win32\Windows.Win32.System.RemoteManagement.h>
#include <win32\Windows.Win32.System.RestartManager.h>
#include <win32\Windows.Win32.System.Restore.h>
#include <win32\Windows.Win32.System.Rpc.h>
#include <win32\Windows.Win32.System.Search.Common.h>
#include <win32\Windows.Win32.System.Search.h>
#include <win32\Windows.Win32.System.SecurityCenter.h>
#include <win32\Windows.Win32.System.ServerBackup.h>
#include <win32\Windows.Win32.System.Services.h>
#include <win32\Windows.Win32.System.SettingsManagementInfrastructure.h>
#include <win32\Windows.Win32.System.SetupAndMigration.h>
#include <win32\Windows.Win32.System.Shutdown.h>
#include <win32\Windows.Win32.System.SideShow.h>
#include <win32\Windows.Win32.System.StationsAndDesktops.h>
#include <win32\Windows.Win32.System.SubsystemForLinux.h>
#include <win32\Windows.Win32.System.SystemInformation.h>
#include <win32\Windows.Win32.System.SystemServices.h>
#include <win32\Windows.Win32.System.TaskScheduler.h>
#include <win32\Windows.Win32.System.Threading.h>
#include <win32\Windows.Win32.System.Time.h>
#include <win32\Windows.Win32.System.TpmBaseServices.h>
#include <win32\Windows.Win32.System.TransactionServer.h>
#include <win32\Windows.Win32.System.UpdateAgent.h>
#include <win32\Windows.Win32.System.UpdateAssessment.h>
#include <win32\Windows.Win32.System.UserAccessLogging.h>
#include <win32\Windows.Win32.System.Variant.h>
#include <win32\Windows.Win32.System.VirtualDosMachines.h>
#include <win32\Windows.Win32.System.WindowsProgramming.h>
#include <win32\Windows.Win32.System.WindowsSync.h>
#include <win32\Windows.Win32.System.WinRT.AllJoyn.h>
#include <win32\Windows.Win32.System.WinRT.Composition.h>
#include <win32\Windows.Win32.System.WinRT.CoreInputView.h>
#include <win32\Windows.Win32.System.WinRT.Direct3D11.h>
#include <win32\Windows.Win32.System.WinRT.Display.h>
#include <win32\Windows.Win32.System.WinRT.Graphics.Capture.h>
#include <win32\Windows.Win32.System.WinRT.Graphics.Direct2D.h>
#include <win32\Windows.Win32.System.WinRT.Graphics.Imaging.h>
#include <win32\Windows.Win32.System.WinRT.h>
#include <win32\Windows.Win32.System.WinRT.Holographic.h>
#include <win32\Windows.Win32.System.WinRT.Isolation.h>
#include <win32\Windows.Win32.System.WinRT.Media.h>
#include <win32\Windows.Win32.System.WinRT.Metadata.h>
#include <win32\Windows.Win32.System.WinRT.ML.h>
#include <win32\Windows.Win32.System.WinRT.Pdf.h>
#include <win32\Windows.Win32.System.WinRT.Printing.h>
#include <win32\Windows.Win32.System.WinRT.Shell.h>
#include <win32\Windows.Win32.System.WinRT.Storage.h>
#include <win32\Windows.Win32.System.WinRT.Xaml.h>
#include <win32\Windows.Win32.System.Wmi.h>
#include <win32\Windows.Win32.UI.Accessibility.h>
#include <win32\Windows.Win32.UI.Animation.h>
#include <win32\Windows.Win32.UI.ColorSystem.h>
#include <win32\Windows.Win32.UI.Controls.Dialogs.h>
#include <win32\Windows.Win32.UI.Controls.h>
#include <win32\Windows.Win32.UI.Controls.RichEdit.h>
#include <win32\Windows.Win32.UI.HiDpi.h>
#include <win32\Windows.Win32.UI.Input.h>
#include <win32\Windows.Win32.UI.Input.Ime.h>
#include <win32\Windows.Win32.UI.Input.Ink.h>
#include <win32\Windows.Win32.UI.Input.KeyboardAndMouse.h>
#include <win32\Windows.Win32.UI.Input.Pointer.h>
#include <win32\Windows.Win32.UI.Input.Radial.h>
#include <win32\Windows.Win32.UI.Input.Touch.h>
#include <win32\Windows.Win32.UI.Input.XboxController.h>
#include <win32\Windows.Win32.UI.InteractionContext.h>
#include <win32\Windows.Win32.UI.LegacyWindowsEnvironmentFeatures.h>
#include <win32\Windows.Win32.UI.Magnification.h>
#include <win32\Windows.Win32.UI.Notifications.h>
#include <win32\Windows.Win32.UI.Ribbon.h>
#include <win32\Windows.Win32.UI.Shell.Common.h>
#include <win32\Windows.Win32.UI.Shell.h>
#include <win32\Windows.Win32.UI.Shell.PropertiesSystem.h>
#include <win32\Windows.Win32.UI.TabletPC.h>
#include <win32\Windows.Win32.UI.TextServices.h>
#include <win32\Windows.Win32.UI.WindowsAndMessaging.h>
#include <win32\Windows.Win32.UI.Wpf.h>
#include <win32\Windows.Win32.UI.Xaml.Diagnostics.h>
#include <win32\Windows.Win32.Web.InternetExplorer.h>
#include <win32\Windows.Win32.Web.MsHtml.h>


#define IID_PPV_ARGS(ppType) win32::guid_of<**(ppType)>(), IID_PPV_ARGS_Helper(ppType)
